run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - gosimple
    - staticcheck
    - unused
    - typecheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
