# Codecov configuration file

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: no

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2  # Allow a 2% drop in overall project coverage
    patch:
      default:
        target: auto
        threshold: 5  # Allow up to a 5% drop in patch coverage

flags:
  unittests:
    paths:
      - ./...  # Matches all files for simplicity
