name: Dependabot CI

on:
  pull_request:
    branches:
      - '**'  # Runs on all branches with PRs

jobs:
  dependabot-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Go environment
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: go mod tidy

      # Step 4: Run tests and generate coverage
      - name: Run tests and generate coverage
        run: go test -v ./... -coverprofile=coverage.out

      # Step 5: Save coverage artifact
      - name: Save coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.out  # Save the coverage file for the secondary workflow
