name: Go CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
    # Step 1: Check out the code without LFS objects first
    - name: Checkout code (without LFS)
      uses: actions/checkout@v4
      with:
        lfs: false

    # Step 2: Set up more efficient LFS cache
    - name: Set up Git LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: |
          .git/lfs
          .git/objects/pack/pack-*.idx
          .git/objects/pack/pack-*.pack
        key: lfs-${{ runner.os }}-${{ hashFiles('.gitattributes') }}-${{ github.sha }}
        restore-keys: |
          lfs-${{ runner.os }}-${{ hashFiles('.gitattributes') }}-
          lfs-${{ runner.os }}-

    # Step 3: Pull LFS objects (will use cache if available)
    - name: Pull LFS objects
      run: |
        git lfs install
        # Apply optimizations via command line instead of .lfsconfig
        git config lfs.concurrenttransfers 1
        git config lfs.batchsize 100
        # Fetch LFS objects
        git lfs pull
        
    # Step 4: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    # Step 5: Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 6: Install golangci-lint
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4
        golangci-lint --version

    # Step 7: Run golangci-lint
    - name: Run golangci-lint
      run: golangci-lint run ./...

    # Step 8: Run tests with coverage
    - name: Run tests and generate coverage
      run: |
        go test -race -v ./... -coverprofile=coverage.out
        go tool cover -func=coverage.out

    # Step 9: Upload coverage to Codecov
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      if: success()
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
        slug: ${{ github.repository }}
        flags: unittests
        fail_ci_if_error: true