name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 4: Install golangci-lint
    - name: Install golangci-lint
      run: |
        curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.63.4
        golangci-lint --version

    # Step 5: Run golangci-lint
    - name: Run golangci-lint
      run: golangci-lint run ./...

    # Step 6: Run tests
    - name: Run tests
      run: go test ./... -v
