name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Remove old Go versions
    - name: Remove old Go versions
      run: sudo rm -rf /opt/hostedtoolcache/go

    # Step 3: Set up Go environment
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20 # Use the version of Go you want

    # Step 4: Install dependencies
    - name: Install dependencies
      run: go mod tidy

    # Step 5: Run tests
    - name: Run tests
      run: go test ./... -v
