name: Build and Release Organize Media

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  build:
    name: Build Binaries
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            ext: ""
            output_name: "organize-media"
            artifact_name: "organize-media-linux"
            zip_name: "organize-media-linux"
          - os: macos-latest
            ext: ""
            output_name: "organize-media"
            artifact_name: "organize-media-mac"
            zip_name: "organize-media-mac"
          - os: windows-latest
            ext: ".exe"
            output_name: "organize-media"
            artifact_name: "organize-media-windows"
            zip_name: "organize-media-windows"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Build binary
        run: go build -o ${{ matrix.output_name }}${{ matrix.ext }}

      - name: Create zip archive
        shell: bash
        run: |
          if [ "${{ runner.os }}" == "Windows" ]; then
            powershell Compress-Archive -Path ${{ matrix.output_name }}${{ matrix.ext }} -DestinationPath ${{ matrix.artifact_name }}-${{ github.ref_name }}.zip
          else
            zip ${{ matrix.artifact_name }}-${{ github.ref_name }}.zip ${{ matrix.output_name }}${{ matrix.ext }}
          fi

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ matrix.artifact_name }}-${{ github.ref_name }}.zip
          asset_name: ${{ matrix.artifact_name }}-${{ github.ref_name }}.zip
          asset_content_type: application/zip