name: Upload Coverage to Codecov

on:
  workflow_run:
    workflows:
      - "Dependabot CI"  # Matches the name of the main workflow
    types:
      - completed         # Runs when the main workflow completes

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code (optional, for metadata like commit hash)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Download the coverage artifact
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage

      # Step 3: Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}  # Use the Codecov token
          files: coverage.out
          slug: ${{ github.repository }}
          flags: unittests
          fail_ci_if_error: true
